### ISSUE TITLE
create folder button?

### ISSUE THREAD

**Issue by legop3** [NaitLee/Takeback-HFS-Template#2]
is there a way to add a "create folder" button in this template? ill be poking around to see if i can hack one in, but i dont quite understand the structure of this template, so i thought it would be worth asking.

**Comment by legop3** [comment]
nevermind. dumb monkey brain just now found the button in the upload menu.

**Comment by NaitLee** [comment]
About one year ago I started adapting Throwback template to a new theme, then Takeback is there.
That time I was not quite understand HTML and so on, so it would be messy since both old and new code and structure exists.
I'm considering to rewrite this template to fit the requirement of development, and also readability, modernity.
