### ISSUE TITLE
Does not support filenames.

### ISSUE THREAD

**Issue by areglos** [NaitLee/Takeback-HFS-Template#6]
I guess it doesn't show because it doesn't support filenames. How can I fix.

Example file name;
51 - 「Dropout Idol Fruit Tart」 タルトな気持ち【フルーツタルト】

https://user-images.githubusercontent.com/10929481/132668220-541588b0-6031-4701-8d0f-895baa1321c1.mp4

**Comment by NaitLee** [comment]
Hi,

I'm 100% sure this is the issue of HFS 2.3m itself: it doesn't support Unicode.

And since your locale is Turkish, which have no encoding to Japanese, those files are not shown in HFS 2.3.

You can try HFS 2.4 RC, which have Unicode support now, the repo of it is [here](https://github.com/rejetto/hfs2), check its release.

Thank you for support :)

**Comment by areglos** [comment]
Thanks.
